### ISSUE TITLE
Do you need license notice?

### ISSUE THREAD

**Issue by mr-cheffy** [TheNetAdmin/Makefile-Templates#10]

**Comment by TheNetAdmin** [comment]
Notice for what purpose?

**Comment by mr-cheffy** [comment]
For "taking / coping" the Makefile

**Comment by TheNetAdmin** [comment]
I see. This project is licensed under MIT, so if using this code in your project, then putting the LICENSE as the comment at the beginning of the Makefiles should be good enough.

**Comment by TheNetAdmin** [comment]
Or any other approaches that follow the MIT license usage should be fine, whichever you prefer.
