### ISSUE TITLE
Use standard variable names

### ISSUE THREAD

**Issue by jxu** [TheNetAdmin/Makefile-Templates#14]
https://www.gnu.org/software/make/manual/make.html#Implicit-Variables provides common variable names which should be followed out of convention.

In particular, the example at https://github.com/TheNetAdmin/Makefile-Templates/blob/884540ba156696ace93e06572a6499c373823aad/SmallProject/Example/Makefile#L2-L3  should use `CC := gcc` or `CXX := g++`, and the common flags variable name is `CFLAGS` or `CXXFLAGS`, depending on if it's C or C++.

**Comment by TheNetAdmin** [comment]
Nice point, I will update these variable names, thanks for the suggestion!

**Comment by jxu** [comment]
Also I'm not sure if having a variable like OBJCFLAGS is necessary when you just pass -c in the recipe (command) itself
