### ISSUE TITLE
`-s` option causes error

### ISSUE THREAD

**Issue by HypoGump** [TheNetAdmin/Makefile-Templates#9]
# Issue
`-s` option in `MAKEFLAGS` causes compilation failure.
```
Building Project
make[1]: *** No rule to make target 's'.  Stop.
/home/ubuntu/Makefile-Templates/MediumProject/Example/config/make.global:18: recipe for target 'src1' failed
make: *** [src1] Error 2
```

# Environment
- GNU Make 4.1. It supports the `-s` option.
- ubuntu 4.15.0-54-generic

The MediumExample can be compiled successfully after removing the `-s` option.

**Comment by TheNetAdmin** [comment]
Should be fixed by b53e947 , feel free to reopen if this problem still exists
